image: docker:24.0.5

stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY: $CI_REGISTRY/nha3/autohero

  DOCKER_HOST: tcp://dockerdind:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

  VITE_API_URL: http://localhost:4000
  VITE_SOLANA_NETWORK: devnet

build:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG == null'
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  services:
    - name: docker:24.0.5-dind
      alias: dockerdind
      command: ["--tls=false"]
  script:
    - cd app
    - docker build --network host --no-cache -t $DOCKER_REGISTRY:dev .
    - docker push $DOCKER_REGISTRY:dev

# deploy_cdn:
#   stage: deploy
#   image: node:18
#   before_script:
#     - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#     - unzip -q awscliv2.zip
#     - ./aws/install
#   script:
#     - cd src/
#     - npm i
#     - npm run deploy
