"""change_time

Revision ID: 4d6024afc62f
Revises: 3822c8b4872f
Create Date: 2024-04-05 00:16:41.962552

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d6024afc62f"
down_revision: Union[str, None] = "3822c8b4872f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event", "created_at", type_=sa.DateTime(timezone=True), nullable=False
    )
    op.alter_column(
        "event", "updated_at", type_=sa.DateTime(timezone=True), nullable=False
    )
    op.alter_column(
        "hero", "created_at", type_=sa.DateTime(timezone=True), nullable=False
    )
    op.alter_column(
        "hero", "updated_at", type_=sa.DateTime(timezone=True), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event", "created_at", type_=sa.DateTime(timezone=False), nullable=False
    )
    op.alter_column(
        "event", "updated_at", type_=sa.DateTime(timezone=False), nullable=False
    )
    op.alter_column(
        "hero", "created_at", type_=sa.DateTime(timezone=False), nullable=False
    )
    op.alter_column(
        "hero", "updated_at", type_=sa.DateTime(timezone=False), nullable=False
    )
    # ### end Alembic commands ###
