[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
autohero = "9V5ggVeRYDwckX9xdhvH9mx7E5sZRcZ5dYiof7mDqkTf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/pomeschenkoanton/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
